name: tamren_tech
description: A remote telerehabilitation in physiotherapy app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The code provided uses standard icons, so these are included by default
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  camera: ^0.10.5+5
  permission_handler: ^11.4.0
  file_picker: ^10.3.7
  google_mlkit_pose_detection: ^0.12.0
  video_player: ^2.8.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/runner_logo.png
    - assets/Background_app.png
    - assets/squat_correct.mp4
    - assets/squat_incorrect.mp4

